apiVersion: apps/v1
kind: Deployment
metadata:
  name: jyp-api-deployment
  labels:
    app: jyp-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jyp-api
  template:
    metadata:
      labels:
        app: jyp-api
    spec:
      containers:
      - name: jyp-api
        image: fuzzysound/journeypiki:20220727170200
        ports:
        - containerPort: 3000