apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      nodeSelector:
        journeypiki/role: mongo
      containers:
        - name: mongo
          image: mongo:5.0
          ports:
            - containerPort: 27017
              name: mongo-port
          volumeMounts:
            - name: mongo-hostpath
              mountPath: /data/db
            - name: mongo-init
              mountPath: /docker-entrypoint-initdb.d
          envFrom:
            - secretRef:
                name: mongo-secret
      volumes:
        - name: mongo-hostpath
          hostPath:
            path: /etc/mongo
        - name: mongo-init
          configMap:
            name: mongo-configmap